name: deploy to lambda
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: build and deploy lambda function
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
        with:
          version: 1.37.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
      - run: sam --version

      - run: sam build -t template.yaml

      - run : |
                sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name serverless-api --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-zceuwfd2ajvw --capabilities CAPABILITY_IAM --region ap-south-1
